#CAP-11 blake3 and sha256 compare benchmark
NexTokenTech/TREX-PoW pull request #11
Opened 2022-05-09 03:15 UTC by kaisuki

1.sha256 Compute and blake3 Compute Impl
2.benchmark for some different difficulties.

2022-05-11 15:36 UTC, yangfh2004 requested changes

2022-05-11 15:36 UTC, yangfh2004 commented on consensus/capsule-pow/benches/pollard_rho_benchmark.rs
> +    // group.bench_function("pollard rho difficulty for 32 use blake3", |b| {
remove all those code if you in use, you may skip it if not running for now. Commenting out big chuck of code is not a good practice.

2022-05-11 15:36 UTC, yangfh2004 commented on pallets/difficulty/src/lib.rs
>  				let difficulty = Self::difficulty().unwrap_or(DIFFICULTY_DEFAULT) as i128 + adj_ts;
Convert difficulty between i128 and u128 is not necessary. You may convert adj_ts to an unsigned integer and a sign. Use the sign to determine the operator (e. g. if negative, use minus, if positive, use plus). So that single conversion will do the job.

2022-05-11 15:36 UTC, yangfh2004 commented on consensus/capsule-pow/benches/pollard_rho_benchmark.rs
> +criterion_group!(benches, criterion_benchmark);
can you create a README.md in the capsule-pow module and post the benchmark results there?

2022-05-12 01:19 UTC, kaisuki commented on consensus/capsule-pow/benches/pollard_rho_benchmark.rs
> +    // group.bench_function("pollard rho difficulty for 32 use blake3", |b| {
Got it！

2022-05-12 01:20 UTC, kaisuki commented on consensus/capsule-pow/benches/pollard_rho_benchmark.rs
> +criterion_group!(benches, criterion_benchmark);
ok

2022-05-12 02:49 UTC, kaisuki commented on pallets/difficulty/src/lib.rs
>  				let difficulty = Self::difficulty().unwrap_or(DIFFICULTY_DEFAULT) as i128 + adj_ts;
replace with the fn 'pub fn checked_add_signed' in u128.

2022-05-12 13:59 UTC, yangfh2004 approved these changes

2022-05-12 13:59 UTC, merged