Cap 21 reward
NexTokenTech/TREX-PoW pull request #12
Opened 2022-05-26 02:52 UTC by kaisuki

Rewards have been tested, as well as changes in the balance of mining accounts.

2022-05-31 17:57 UTC, yangfh2004 requested changes

2022-05-31 17:57 UTC, yangfh2004 commented on node/src/command.rs
> +					Role::Light => service::new_full(config, false,cli.author.as_ref().map(|s| s.as_str())),
This part is misleading, shall we fix it? the Role::Light is not implemented here, the Role::Full will be full and add the miner role.

2022-05-31 17:57 UTC, yangfh2004 commented on runtime/src/genesis.rs
> +			rewards: 60 * DOLLARS,
where this "60" comes from, please don't use magic number, instead, use const number.

2022-05-31 17:57 UTC, yangfh2004 commented on pallets/rewards/src/migrations.rs
> +pub struct CurvePointV0<BlockNumber, Balance> {
Do we need this? if not, please remove those useless code.

2022-05-31 17:57 UTC, yangfh2004 commented on pallets/rewards/src/lib.rs
> +	pub fn do_update_reward_locks(
remove "do" from the naming just use "update_reward_locks"

2022-05-31 17:57 UTC, yangfh2004 commented on pallets/rewards/src/lib.rs
> +			Default::default()
what is the default value? why use default here?

2022-05-31 17:57 UTC, yangfh2004 commented on runtime/src/lib.rs
> +		let locked_reward = total_reward.saturating_sub(1 * DOLLARS);
why subtract 1 here?

2022-05-31 17:57 UTC, yangfh2004 commented on runtime/src/lib.rs
> +				total_lock_period = 100 * DAYS;
where is the 100 and 10 magic number comes from?

2022-06-02 03:47 UTC, kaisuki commented on runtime/src/genesis.rs
> +			rewards: 60 * DOLLARS,
move it to cp_constants

2022-06-02 03:48 UTC, kaisuki commented on pallets/rewards/src/migrations.rs
> +pub struct CurvePointV0<BlockNumber, Balance> {
remove migrations.rs and StorageVersion relation code

2022-06-02 03:49 UTC, kaisuki commented on runtime/src/lib.rs
> +		let locked_reward = total_reward.saturating_sub(1 * DOLLARS);
at least 1 CPS will always be without locks, so that the miner can always have money to pay for transaction fees

2022-06-02 03:49 UTC, kaisuki commented on runtime/src/lib.rs
> +				total_lock_period = 100 * DAYS;
For the remainder of the reward, it has a total lock of 100 days, and the locks expire every 10 days releasing 10% of the reward.

2022-06-02 03:50 UTC, kaisuki commented on pallets/rewards/src/lib.rs
> +	pub fn do_update_reward_locks(
ok

2022-06-02 04:00 UTC, kaisuki commented on node/src/command.rs
> +					Role::Light => service::new_full(config, false,cli.author.as_ref().map(|s| s.as_str())),
remove light node mode,only full and authority mode is left.

2022-06-06 17:41 UTC, merged