Cap 12 keychains
NexTokenTech/TREX-PoW pull request #7
Opened 2022-04-22 14:07 UTC by kaisuki

keychain stored in json file read and write

2022-04-27 18:07 UTC, yangfh2004 requested changes

2022-04-27 18:07 UTC, yangfh2004 commented on consensus/capsule-pow/Cargo.toml
> +elgamal_capsule = {version = "0.1.0", git = "https://github.com/NexTokenTech/elgamal_capsule.git", branch = "CAP-15-traits"}
please update here after the CAP-15 is merged.

2022-04-27 18:07 UTC, yangfh2004 commented on consensus/capsule-pow/Cargo.toml
> +elgamal_capsule = {version = "0.1.3", git = "https://github.com/NexTokenTech/elgamal_capsule.git", branch = "CAP-15-traits"}
branch is merged, you the master branch here.

2022-04-27 18:07 UTC, yangfh2004 commented on consensus/capsule-pow/src/generic.rs
> +use elgamal_capsule::elgamal::PublicKey;
In next pr for elgamal_capsule, reexport the basic structure PublicKey to the lib level. You don't have to do it now.

2022-04-27 18:07 UTC, yangfh2004 commented on node/src/service.rs
> +	let keychain_map_tuple = handle_pubkey(&mut keychain_map, &difficulty, &best_number);
you may do this:
let out (last_pubkey, keychain_map_final) = handle_pubkey(...)

2022-04-27 18:07 UTC, yangfh2004 commented on node/src/service.rs
> +	(last_pubkey, keychain_map.to_owned())
I don't understand why you have to return the keychain_map, since it passed by reference, it have already been updated.

2022-04-27 18:07 UTC, yangfh2004 commented on node/src/service.rs
> +	for difficulty_tmp in MIN_DIFFICULTY..(MAX_DIFFICULTY - 1) {
I think the code design is kind of redundant, you just need to update the keychain based on the best block number and pick up the corresponding public key based on current difficulty. The moves between different variables are not necessary since you are passing mutable references of the same piece of hash map...

2022-04-27 18:07 UTC, yangfh2004 commented on node/src/service.rs
> +						let last_pubkey_for_cur_difficulty =
The naming is awkward. Say "new_pubkey" or "updated_pubkey" since you just update keychains.
I suggest you split the update_keychains_with_difficulty into two parts:
1. update the keychain for all difficulty levels based on current best block number. return the hash map.
2. pick up the updated pubkey for mining based on current difficulty.

2022-04-27 18:07 UTC, yangfh2004 commented on node/src/service.rs
> +	// remove old file,make sure the file is clear for writing.
if the writer is not incremental, why do you have to remove the old one? you will overwrite it anyway.

2022-04-27 18:07 UTC, yangfh2004 commented on node/src/service.rs
> +		Err(_) => {},
throw warning at least for IO problem.

2022-04-27 18:07 UTC, yangfh2004 commented on node/src/service.rs
> +pub fn update_keychains_with_difficulty(
This function contains three parts - file IO, keychain update and choosing the pubkey based on current difficulty. I suggest you only do the first two parts and return the hash map . In the future, the file IO operation can be async for better performance (not necessary in this PR).

2022-04-27 18:07 UTC, yangfh2004 commented on node/src/service.rs
> +pub fn handle_pubkey(
You don't have to return the last_pubkey since it has been encoded into the hash map. You may just decode it from the hash map based on chosen difficulty.

2022-04-28 04:19 UTC, kaisuki commented on consensus/capsule-pow/src/generic.rs
> +use elgamal_capsule::elgamal::PublicKey;
marked

2022-04-28 06:28 UTC, kaisuki commented on node/src/service.rs
> +	let keychain_map_tuple = handle_pubkey(&mut keychain_map, &difficulty, &best_number);
ok don't have to return the tuple now.

2022-04-28 06:28 UTC, kaisuki commented on node/src/service.rs
> +	(last_pubkey, keychain_map.to_owned())
fixed

2022-04-28 06:31 UTC, kaisuki commented on node/src/service.rs
> +	for difficulty_tmp in MIN_DIFFICULTY..(MAX_DIFFICULTY - 1) {
fixed

2022-04-28 14:41 UTC, yangfh2004 approved these changes

2022-04-28 14:41 UTC, merged